name: rfcat-phocean
version: commit-109f887
summary: Rfcat
description: |
  Rfcat is a swiss-army knife of ISM band radio.
base: core18
confinement: strict
grade: stable

parts:
  rfcat:
    source: https://github.com/atlas0fd00m/rfcat.git
    plugin: python
    python-version: python2
    build-packages:
      - python-pip
    stage-packages:
      - libusb-1.0-0
      - libpng-dev
      - sdcc
      - libfreetype6-dev
      - ipython
      - python-usb
      - python-serial
      - libtinfo5
    
apps:
  rfcat:
    command: bin/rfcat
    plugs: [home,network-bind,mount-observe,system-observe,raw-usb,hardware-observe,hidraw]
  rfcat-bootloader:
    command: bin/rfcat_bootloader
    plugs: [home]
